---

# roles/grafana/tasks/main.yml

- name: Importuj klucz GPG Grafana
  ansible.builtin.apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present
  # Gdy uruchomisz to zadanie, powinno być ok=1, changed=0 (jeśli klucz już jest)
  # lub ok=1, changed=1 (jeśli klucz jest dodawany)
  # To jest kluczowe, aby zapobiec błędowi "NO_PUBKEY"

- name: Dodaj repozytorium Grafana # Twoje istniejące zadanie
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    update_cache: yes # Upewnij się, że to jest ustawione na 'yes'
    
#- name: Dodaj repozytorium Grafana
# apt_repository:
#   repo: deb https://packages.grafana.com/oss/deb stable main
#  state: present
#  filename: grafana

#name: Dodaj klucz GPG dla Grafana
#apt_key:
#url: https://packages.grafana.com/gpg.key
#state: present

- name: Instalacja Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes

- name: Skopiuj datasource config
  copy:
    src: "{{ playbook_dir }}/../files/datasource.yml"
    dest: /etc/grafana/provisioning/datasources/datasource.yml
    owner: grafana
    group: grafana
    mode: '0644'

- name: Upewnij się, że usługa Grafana działa
  service:
    name: grafana-server
    state: started
    enabled: true

