---
- name: Pobierz Node Exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz

- name: Rozpakuj Node Exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /opt/
    remote_src: yes

- name: Przenieś plik binarny
  copy:
    remote_src: yes
    src: /opt/node_exporter-1.7.0.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    mode: '0755'

- name: Utwórz usługę systemd
  copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=default.target
  notify: Restart Node Exporter

- name: Uruchom usługę Node Exporter
  systemd:
    name: node_exporter
    enabled: true
    state: started

