global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.0.55:9100', '192.168.0.103:9100'] # Upewnij się, że Node Exporter jest na 192.168.0.103 na 9100, a nie 9182

 # - job_name: 'centos9' # Jeśli masz taki host, dodaj
 # static_configs:
 #     - targets: ['192.168.0.101:9100']

  - job_name: 'windows11' # Używałem 9182 dla WMI exportera, Node exporter dla Windows to też 9100. Potwierdź, co masz zainstalowane.
    static_configs:
      - targets: ['192.168.0.103:9182']